name: Deploy Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PORT: ${{ secrets.PORT }}
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
  LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
  LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
  NODE_ENV: ${{ secrets.NODE_ENV }}

jobs:
  deploy:
    name: Deploy Server
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create .env file
        run: |
          New-Item -Path . -Name ".env" -ItemType "file" -Force
          Add-Content -Path .env "PORT=${{ secrets.PORT }}"
          Add-Content -Path .env "SUPABASE_URL=${{ secrets.SUPABASE_URL }}"
          Add-Content -Path .env "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}"
          Add-Content -Path .env "LINE_ACCESS_TOKEN=${{ secrets.LINE_ACCESS_TOKEN }}"
          Add-Content -Path .env "LINE_CHANNEL_SECRET=${{ secrets.LINE_CHANNEL_SECRET }}"
          Add-Content -Path .env "JWT_SECRET=${{ secrets.JWT_SECRET }}"
          Add-Content -Path .env "CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }}"
          Add-Content -Path .env "NODE_ENV=${{ secrets.NODE_ENV }}"
        shell: pwsh

      - name: Build and push Docker Image
        run: |
          docker build -t boomtris/boom-tris-hospital-backend:latest -f backend/Dockerfile backend
          docker push boomtris/boom-tris-hospital-backend:latest
        shell: pwsh
